interface LogoProps {
  size?: number;
  className?: string;
}

/**
 * App-icon-style logo. Renders the same artwork the iOS / Android home
 * screens use, downscaled. Sourced from public/pwa-64x64.png (generated by
 * @vite-pwa/assets-generator from the master image in store-assets/).
 */
export function Logo({ size = 28, className }: LogoProps) {
  return (
    <img
      src={import.meta.env.BASE_URL + 'pwa-64x64.png'}
      width={size}
      height={size}
      alt=""
      aria-hidden="true"
      className={'rounded-md ' + (className ?? '')}
      style={{ width: size, height: size }}
    />
  );
}
